services:
  - type: web
    name: farmtrak-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: 17
      # Add these database environment variables
      - key: JDBC_DATABASE_URL
        sync: false 
      - key: JDBC_DATABASE_USERNAME
        sync: false
      - key: JDBC_DATABASE_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_APP_PASSWORD
        sync: false